eureka:
  client:
    service-url:
#      defaultZone: http://${cloud.eureka.host}:8761/eureka/
      defaultZone: http://${cloud.eureka.host}:8761/eureka/,http://${cloud.eureka.host2}:8761/eureka/
#      defaultZone: http://192.168.148.57:8761/eureka/,http://192.168.148.63:8761/eureka/

spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:/opt/oracle/tomcat/frms/git-config
#        git:
#          uri: C:/deploy/test/git-config
#            repos:
#              local: file://C:/deploy/test/git-config
#          uri: file:////opt/oracle/tomcat/frms/git-config

logging:
  path: ../logs/

cloud:
  eureka:
    host: 127.0.0.1
    host2: 127.0.0.1