eureka:
  client:
    service-url:
      defaultZone: http://${cloud.eureka.host}:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          username: frmsconfig
          password: acSBdfdsage9180kt_0
          uri: http://120.27.228.158/frms/frms-config.git
          basedir: C:/deploy/test/git-config2
cloud:
  eureka:
    host: 127.0.0.1
    
logging:
  path: C:\logs\