eureka:
  client:
    service-url:
      defaultZone: http://${cloud.eureka.host}:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          username: 0
          password: 0
          uri: http:///frms/frms-config.git
#          basedir: C:/deploy/test/git-config2
cloud:
  eureka:
    host: 127.0.0.1
    
logging:
  path: /usr/local/porter/logs/
