eureka:
  client:
    service-url:
      defaultZone: http://${cloud.eureka.host}:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
         username: 0
          password: 0
          uri: http:///frms/frms-config.git
          basedir: /usr/local/porter/porter-config/git_dir

logging:
  path: /usr/local/frms/logs/
